function sour() {
	document.getElementById('text').innerHTML='<h2>Sour</h2><br><p style = "line-height: 200%;">In a large saucepan, heat the oil over moderate heat. Add the chicken and sauté for 4 minutes or until no longer pink on the outside. Add the soaked mushrooms, fresh mushrooms, green onions, stock, soy sauce, honey, and mushroom soaking liquid. Bring the sauce pan mixture to a simmer.In a large saucepan, heat the oil over moderate heat. Add the chicken and sauté for 4 minutes or until no longer pink on the outside. Add the soaked mushrooms, fresh mushrooms, green onions, stock, soy sauce, honey, and mushroom soaking liquid. Bring the sauce pan mixture to a simmer.In a large saucepan, heat the oil over moderate heat. Add the chicken and sauté for 4 minutes or until no longer pink on the outside. Add the soaked mushrooms, fresh mushrooms, green onions, stock, soy sauce, honey, and mushroom soaking liquid. Bring the sauce pan mixture to a simmer.In a large saucepan, heat the oil over moderate heat. Add the chicken and sauté for 4 minutes or until no longer pink on the outside. Add the soaked mushrooms, fresh mushrooms, green onions, stock, soy sauce, honey, and mushroom soaking liquid. Bring the sauce pan mixture to a simmer.<br><br></p>';
	
}

function sweet() {
	document.getElementById('text').innerHTML='<h2>Sweet</h2><br><p style = "line-height: 200%;">In a small saucepan, bring 1 cup of the water to a boil. Place the bamboo shoots in a small heatproof bowl and pour 1/2 cup of the boiling water over them; let soak for 5 minutes then drain. Add the dried mushrooms to the water to the water remaining in the saucepan and let soak for 15 minutes. Drain the mushrooms through a sieve, reserving the soaking liquid. Slice the mushrooms, discarding the stems.<br>In a small saucepan, bring 1 cup of the water to a boil. Place the bamboo shoots in a small heatproof bowl and pour 1/2 cup of the boiling water over them; let soak for 5 minutes then drain. Add the dried mushrooms to the water to the water remaining in the saucepan and let soak for 15 minutes. Drain the mushrooms through a sieve, reserving the soaking liquid. Slice the mushrooms, discarding the stems.<br><br> </p>';	
}

function bitter() {
	document.getElementById('text').innerHTML='<h2>Bitter</h2><br><p style = "line-height: 200%;">Meanwhile, in a small bowl, mix the cornstarch with the remaining 1/4 cup water. Stir the cornstarch mixture into the simmering soup and cook for 5 minutes. Stir in the tofu, vinegar, and red pepper sauce. Cook until the tofu is heated through.<br>Meanwhile, in a small bowl, mix the cornstarch with the remaining 1/4 cup water. Stir the cornstarch mixture into the simmering soup and cook for 5 minutes. Stir in the tofu, vinegar, and red pepper sauce. Cook until the tofu is heated through.<br>Stir in the cooked pork along with green pepper/onion mixture, pineapple chunks along with the juice from the can; return to a simmer.<br>Stir in the cooked pork along with green pepper/onion mixture, pineapple chunks along with the juice from the can; return to a simmer.<br></p>';
}

function spicy() {
	document.getElementById('text').innerHTML='<h2>Spicy</h2><br><p style = "line-height: 200%;">Place the cubes pork in a medium bowl, add in 1 teaspoon salt, 1/4 teaspoon sugar and 1 teaspoon soy sauce; using clean hands toss well to combine, then add in 1 egg white and toss once again.<br>Mix in chopped green onion; cover and refrigerate for 1 or more hours.<br>heat 1 quart of oil to 365 degrees F in a large heavy pot or in an electric deep-fryer.<br>Remove the pork from the fridge and toss with 1/2 cup cornstarch.<br>Stir in the cooked pork along with green pepper/onion mixture, pineapple chunks along with the juice from the can; return to a simmer.Stir in the cooked pork along with green pepper/onion mixture, pineapple chunks along with the juice from the can; return to a simmer.</p>';
}

function salty() {
	document.getElementById('text').innerHTML='<h2>Salty</h2><br><p style = "line-height: 200%;">fry the pork in hot oil about 8 minutes or until evenly browned (do not over crowd the pot fry in 2 batches or three if necessary) drain on paper towels or on a rack.<br>Heat 1 tablespoon oil in a large wok over medium heat; stir in bell pepper strips, onion and crushed chil flakes; stir fry until just tender, then season with 1/4 teaspoon sugar and salt to taste; remove from heat and set aside.<br>For the sweet and sour sauce; in a large skillet or saucepan combine 1 cup water with 1/8 to 1/4 teaspoon salt, 3/4 cup sugar, apple cider vinegar, ketchup and 1/2 teaspoon soy sauce; bring to a boil.<br>Stir in the cooked pork along with green pepper/onion mixture, pineapple chunks along with the juice from the can; return to a simmer.</p>';
}

function leave() {
	document.getElementById('text').innerHTML='<h2>Five Flavors</h2><br><p style = "line-height: 200%;">A number of different styles contribute to Chinese cuisine but perhaps the best known and most influential are Cantonese cuisine, Shandong cuisine, Jiangsu cuisine (specifically Huaiyang cuisine) and Sichuan cuisine. These styles are distinctive from one another due to factors such as availability of resources, climate, geography, history, cooking techniques and lifestyle. One style may favour the use of garlic and shallots over chili and spices, while another may favour preparing seafood over other meats and fowl. Jiangsu cuisine favours cooking techniques such as braising and stewing, while Sichuan cuisine employs baking.<br>Based on the raw materials and ingredients used, the method of preparation and cultural differences, a variety of foods with different flavors and textures are prepared in different regions of the country. Many traditional regional cuisines rely on basic methods of preservation such as drying, salting, pickling and fermentation.<br>Cooking is an art, recipes sprout out of creativity and imagination or even borrowing a leaf from other cultures.<p>';
}